version: '3'
services:
  nginx:
    image: ${FRONTEND_IMAGE_NAME}:${VERSION}
    container_name: Frontend
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8089:80"
    volumes:
      - ${APP_HOME}/www.conf:/etc/nginx/conf.d/default.conf # 挂载自定义配置文件
      - /etc/localtime:/etc/localtime:ro
    networks:
      - encryption-network
    restart: always
    depends_on:
      - backend

  backend:
    image: ${BACKEND_IMAGE_NAME}:${VERSION}  # 替换为你的后台服务镜像
    container_name: backend
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Shanghai
    expose:
      - "8080"  # 替换为你的后台服务端口
    networks:
      - encryption-network

networks:
  encryption-network:
    driver: bridge  # 使用 bridge 网络模式
