- name: Install LVM2 based on OS type
  hosts: test
  become: true
  tasks:
    - name: Gather facts
      setup:

    - name: Install LVM2 on RHEL-based systems
      yum:
        name: lvm2
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Install LVM2 on Debian-based systems
      apt:
        name: lvm2
        state: present
      when: ansible_facts['os_family'] == "Debian"
