---
- name: Deploy Docker Compose Application
  hosts: test  # 替换为你的目标主机组
  become: true  # 提升权限
  vars_files:
    - vars.yaml
  tasks:
    - name: create folder
      command: "mkdir -p {{ item.des }}"
      loop: "{{ stroge_path }}"
    - name: Copy Docker Compose file
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.des }}/{{ item.src }}"  # 目标路径
      loop: "{{ stroge_path }}"
    - name: Run Docker Compose
      command: "{{ item.cmd }}"
      args:
        chdir: "{{ item.path }}"
      loop: "{{ stroge_path }}"