---
- name: Query Proxmox VM Config
  hosts: localhost
  gather_facts: no
  vars:
    proxmox_api_url: "https://:8007/api2/json/backup"
    proxmox_api_token: "PBSAPIToken=xxxx@pbs!test:4ed6053d-6577-4f7c-a598-1d03d16ecec5"

  tasks:
    - name: Get VM Config
      uri:
        url: "{{ proxmox_api_url }}"
        method: GET
        headers:
          Authorization: "{{ proxmox_api_token }}"
        validate_certs: no
      register: vm_config

    - name: Show VM Config
      debug:
        var: vm_config.json
